export const data = {
    cms_documents: [
        {
            "alula_aboutcontent": [
                {
                    "DocumentShowInMenu": false,
                    "NodeParentID": 8,
                    "DocumentName": "About AR",
                    "DocumentForeignKeyValue": 2,
                    "NodeOwner": 53,
                    "DocumentIsWaitingForTranslation": false,
                    "DocumentLastPublished": null,
                    "DocumentCheckedOutVersionHistoryID": null,
                    "DocumentABTestConfiguration": null,
                    "DocumentPageDescription": null,
                    "title": "About",
                    "DocumentCustomData": null,
                    "DocumentWorkflowActionStatus": null,
                    "DocumentSKUShortDescription": null,
                    "DocumentContent": "",
                    "DocumentSearchExcluded": null,
                    "DocumentUnpublishedRedirectUrl": null,
                    "DocumentSKUName": null,
                    "NodeGUID": "1353f708-29f6-45cd-8ed2-1ba49b1adfff",
                    "DocumentPublishTo": null,
                    "DocumentTagGroupID": null,
                    "DocumentPageKeyWords": null,
                    "NodeACLID": 2,
                    "NodeClassID": 5540,
                    "IsSecuredNode": null,
                    "NodeHasChildren": false,
                    "DocumentWorkflowCycleGUID": "04b80e57-d3ff-4ce5-9f9e-40cdd8a48ba3",
                    "ClassDisplayName": "About Content",
                    "DocumentTags": null,
                    "NodeName": "About",
                    "DocumentPublishFrom": null,
                    "DocumentModifiedWhen": "2023-08-25T18:16:50.6853297+05:00",
                    "DocumentPageBuilderWidgets": null,
                    "NodeLevel": 2,
                    "DocumentLastVersionNumber": null,
                    "NodeSiteID": 2,
                    "DocumentWorkflowStepID": null,
                    "DocumentCulture": "ar-SA",
                    "DocumentID": 11,
                    "AboutContentID": 2,
                    "DocumentPageTitle": null,
                    "DocumentPageTemplateConfiguration": null,
                    "NodeOrder": 1,
                    "DocumentPublishedVersionHistoryID": null,
                    "DocumentIsArchived": false,
                    "NodeOriginalNodeID": 10,
                    "DocumentCreatedByUserID": 53,
                    "ClassName": "Alula.AboutContent",
                    "NodeAlias": "About",
                    "DocumentCreatedWhen": "2023-08-25T15:58:57.0326406+05:00",
                    "NodeLinkedNodeID": null,
                    "DocumentModifiedByUserID": 53,
                    "NodeHasLinks": false,
                    "DocumentSKUDescription": null,
                    "DocumentGUID": "098c2f5b-7043-4d93-a054-a910d906e3d9",
                    "DocumentCanBePublished": true,
                    "NodeAliasPath": "/Home/About",
                    "NodeIsACLOwner": false,
                    "DocumentCheckedOutByUserID": null,
                    "NodeLinkedNodeSiteID": null,
                    "DocumentNodeID": 10,
                    "content": "The inaugural AlUla World Archaeology Summit will convene innovators from archaeology and other disciplines to foster cross-cultural and interdisciplinary discussions. Together, we will explore the value of understanding the past, of using that knowledge to inform the present, and to build a resilient future.<br />\r\n<br />\r\nIt is a global platform promoting archaeology and cultural heritage to wider audiences, and inspiring people to co-create visionary, heritage-based solutions to contemporary problems across sectors.<br />\r\n<br />\r\nAt the same time, invited experts from outside the field of archaeology and its traditional allied disciplines will contribute their unique perspectives and help enhance the field. By convening a diverse group of thinkers and doers, the Summit will enrich the archaeological community and help protect our shared heritage.",
                    "preview_image": "~/getmedia/0e7c9dfc-7bb3-4865-84b9-fddc60f6fb8a/bg-below-img.jpg?width=663&height=742&ext=.jpg",
                    "NodeCustomData": null,
                    "image": null,
                    "DocumentCheckedOutWhen": null,
                    "NodeID": 10,
                    "NodeSKUID": null
                }
            ]
        },
        {
            "alula_homepage": [
                {
                    "DocumentShowInMenu": false,
                    "NodeParentID": 7,
                    "DocumentName": "Home",
                    "DocumentForeignKeyValue": 2,
                    "NodeOwner": 53,
                    "DocumentIsWaitingForTranslation": false,
                    "DocumentLastPublished": null,
                    "DocumentCheckedOutVersionHistoryID": null,
                    "DocumentABTestConfiguration": null,
                    "DocumentPageDescription": null,
                    "meta_title": null,
                    "page_title": "Home Page",
                    "DocumentCustomData": null,
                    "DocumentWorkflowActionStatus": null,
                    "DocumentSKUShortDescription": null,
                    "DocumentContent": "",
                    "NodeAlias": "Home",
                    "DocumentUnpublishedRedirectUrl": null,
                    "DocumentSKUName": null,
                    "NodeGUID": "cffbdd7b-6163-4ac7-b9fb-93ec907554e4",
                    "DocumentPublishTo": null,
                    "DocumentPageKeyWords": null,
                    "NodeACLID": 2,
                    "NodeClassID": 5536,
                    "IsSecuredNode": null,
                    "NodeHasChildren": true,
                    "DocumentWorkflowCycleGUID": "a9a15476-0784-48f4-8f2f-23b6918c9f4a",
                    "ClassDisplayName": "Home Page",
                    "DocumentTags": null,
                    "NodeName": "Home",
                    "DocumentPublishFrom": null,
                    "DocumentModifiedWhen": "2023-08-25T15:58:52.2287284+05:00",
                    "DocumentPageBuilderWidgets": null,
                    "NodeLevel": 1,
                    "DocumentLastVersionNumber": null,
                    "NodeSiteID": 2,
                    "DocumentWorkflowStepID": null,
                    "DocumentCulture": "ar-SA",
                    "DocumentID": 10,
                    "DocumentPageTitle": null,
                    "DocumentPageTemplateConfiguration": null,
                    "NodeOrder": 1,
                    "DocumentPublishedVersionHistoryID": null,
                    "DocumentIsArchived": false,
                    "NodeOriginalNodeID": 8,
                    "DocumentCreatedByUserID": 53,
                    "ClassName": "Alula.HomePage",
                    "DocumentCreatedWhen": "2023-08-25T15:58:52.2287284+05:00",
                    "NodeLinkedNodeID": null,
                    "DocumentModifiedByUserID": 53,
                    "NodeHasLinks": false,
                    "DocumentSKUDescription": null,
                    "HomePageID": 2,
                    "DocumentGUID": "462034fb-c8c3-45c7-beb6-0fa785c16437",
                    "DocumentSearchExcluded": null,
                    "NodeAliasPath": "/Home",
                    "meta_description": null,
                    "NodeIsACLOwner": false,
                    "DocumentCheckedOutByUserID": null,
                    "NodeLinkedNodeSiteID": null,
                    "DocumentNodeID": 8,
                    "DocumentTagGroupID": null,
                    "NodeCustomData": null,
                    "DocumentCanBePublished": true,
                    "DocumentCheckedOutWhen": null,
                    "NodeID": 8,
                    "NodeSKUID": null
                }
            ]
        },
        {
            "alula_videobanner": [
                {
                    "DocumentShowInMenu": false,
                    "NodeParentID": 8,
                    "DocumentName": "Video Banner",
                    "DocumentForeignKeyValue": 2,
                    "NodeOwner": 53,
                    "DocumentIsWaitingForTranslation": false,
                    "DocumentLastPublished": null,
                    "DocumentCheckedOutVersionHistoryID": null,
                    "DocumentABTestConfiguration": null,
                    "DocumentPageDescription": null,
                    "DocumentCustomData": null,
                    "DocumentWorkflowActionStatus": null,
                    "DocumentSKUShortDescription": null,
                    "DocumentContent": "",
                    "NodeAlias": "Video-Banner",
                    "DocumentUnpublishedRedirectUrl": null,
                    "DocumentSKUName": null,
                    "NodeGUID": "cd1d4d0b-e7f9-43ec-88b2-5fbe43510b5c",
                    "DocumentPublishTo": null,
                    "DocumentPageKeyWords": null,
                    "NodeACLID": 2,
                    "NodeClassID": 5537,
                    "IsSecuredNode": null,
                    "NodeHasChildren": false,
                    "DocumentWorkflowCycleGUID": "11f38424-e2cc-4ce2-a3c2-f56f91d9451e",
                    "ClassDisplayName": "Video Banner",
                    "DocumentTags": null,
                    "NodeName": "d",
                    "DocumentPublishFrom": null,
                    "DocumentModifiedWhen": "2023-08-25T15:59:14.1150351+05:00",
                    "DocumentPageBuilderWidgets": null,
                    "NodeLevel": 2,
                    "DocumentLastVersionNumber": null,
                    "NodeSiteID": 2,
                    "DocumentWorkflowStepID": null,
                    "DocumentCulture": "ar-SA",
                    "DocumentID": 12,
                    "DocumentPageTitle": null,
                    "DocumentPageTemplateConfiguration": null,
                    "NodeOrder": 2,
                    "DocumentPublishedVersionHistoryID": null,
                    "DocumentIsArchived": false,
                    "NodeOriginalNodeID": 9,
                    "DocumentCreatedByUserID": 53,
                    "ClassName": "Alula.VideoBanner",
                    "video_link": "https://www.youtube.com/watch?v=JNO8HVkDr-U",
                    "DocumentCreatedWhen": "2023-08-25T15:59:14.1150351+05:00",
                    "NodeLinkedNodeID": null,
                    "DocumentModifiedByUserID": 53,
                    "NodeHasLinks": false,
                    "DocumentSKUDescription": null,
                    "PageBannerID": 2,
                    "DocumentGUID": "765f6616-93d2-4e47-81a7-0a1eefb05918",
                    "DocumentSearchExcluded": null,
                    "NodeAliasPath": "/Home/Video-Banner",
                    "NodeIsACLOwner": false,
                    "DocumentCheckedOutByUserID": null,
                    "NodeLinkedNodeSiteID": null,
                    "DocumentNodeID": 9,
                    "DocumentTagGroupID": null,
                    "NodeCustomData": null,
                    "DocumentCanBePublished": true,
                    "DocumentCheckedOutWhen": null,
                    "NodeID": 9,
                    "NodeSKUID": null
                }
            ]
        }
    ]
}